openapi: 3.0.3
info:
  version: 1.0.0
  title: Patient Scheduling System
  contact:
    name: Julian Stpehens
    email: hello@julianstephens.net
    url: "http://julianstephens.net/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  description:
    $ref: ./README.md
tags:
  - name: patients
    description: Operations about patients.
  - name: employees
    description: Operations about employees.
  - name: appointments
    description: Operations about appointments.
  - name: medications
    description: Operations about medications.
  - name: pharmacies
    description: Operations about pharmacies.
paths:
  $ref: paths/Patients.yaml
    $ref: "paths/Patients@{Patient}.yaml"
  $ref: paths/Employees.yaml
    $ref: "paths/Employees@{Employee}.yaml"
  $ref: paths/Appointments.yaml
    $ref: "paths/Appointments@{Appointment}.yaml"
  $ref: paths/Medications.yaml
    $ref: "paths/Medications@{Medication}.yaml"
  $ref: paths/Pharmacies.yaml
    $ref: "paths/Pharmacies@{Pharmacy}.yaml"
