openapi: 3.0.3
info:
  version: 1.0.0
  title: Patient Scheduling System
  contact:
    name: Julian Stpehens
    email: hello@julianstephens.net
    url: "http://julianstephens.net/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  description:
    $ref: ./README.md
tags:
  - name: patients
    description: Operations about patients.
  - name: employees
    description: Operations about employees.
  - name: appointments
    description: Operations about appointments.
  - name: medications
    description: Operations about medications.
  - name: pharmacies
    description: Operations about pharmacies.
paths:
  /patients:
    $ref: paths/Patients.yaml
  /patients/{patientId}:
    $ref: paths/Patients@{Patient}.yaml
  /patients/{patientId}/appointments:
    $ref: paths/PatientsAppointments.yaml
  /patients/{patientId}/appointments/{appointmentId}:
    $ref: paths/PatientsAppointments@{Appointment}.yaml
  /patients/{patientId}/medications:
    $ref: paths/PatientsMedications.yaml
  /patients/{patientId}/medications/{medicationId}:
    $ref: paths/PatientsMedications@{Medication}.yaml
  /patients/{patientId}/pharmacies:
    $ref: paths/PatientsPharmacies.yaml
  /patients/{patientId}/pharmacies/{pharmacyId}:
    $ref: paths/PatientsPharmacies@{Pharmacy}.yaml
  /employees:
    $ref: paths/Employees.yaml
  /employees/{employeeId}:
    $ref: "paths/Employees@{Employee}.yaml"
  /employees/{employeeId}/appointments:
    $ref: paths/EmployeesAppointments.yaml
  /employees/{employeeId}/appointments/{appointmentId}:
    $ref: paths/EmployeesAppointments@{Appointment}.yaml
  /appointments:
    $ref: paths/Appointments.yaml
  /appointments/{appointmentId}:
    $ref: "paths/Appointments@{Appointment}.yaml"
  /medications:
    $ref: paths/Medications.yaml
  /medications/{medicationId}:
    $ref: "paths/Medications@{Medication}.yaml"
  /pharmacies:
    $ref: paths/Pharmacies.yaml
  /pharmacies/{pharmacyId}:
    $ref: "paths/Pharmacies@{Pharmacy}.yaml"
